corolla_data <- read.csv(file.choose())
attach(corolla_data)
corolla_pred <- cbind(Price,Age_08_04,KM,HP,cc,Doors,Gears,Quarterly_Tax,Weight)
class(corolla_pred)
corolla_pred1 <- as.data.frame(corolla_pred)
class(corolla_pred1)
attach(corolla_pred1)
summary(corolla_pred1)
plot(Age_08_04, Price)
plot(KM, Price)
plot(HP, Price)
plot(cc, Price)
plot(Doors, Price)
plot(Gears, Price)
plot(Quarterly_Tax, Price)
plot(Weight, Price)
pairs(corolla_pred1)
cor(corolla_pred1)
#simple linear regression model
model <- lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight)
summary(model)
#r2 = 0.86
model1 <-lm(Price~Age_08_04+KM+HP+Gears+Quarterly_Tax+Weight)
summary(model1)
#r2 same even after not considering cc
#r2 = 0.86
library(corpcor)
cor2pcor(cor(corolla_pred1))
library(mvinfluence)
library(car)
influence.measures(model)
influenceIndexPlot(model, id.n=3)
influencePlot(model, id.n=3) 
#Regression after deleting the 81st observation, which is influential observation
model2 <- lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight,data=corolla_pred1[-81,])
summary(model2)
#r2 = 0.86
vif(model1)
plot(Age_08_04,KM, col="dodgerblue4",pch=20)
plot(HP,cc, col="dodgerblue4",pch=20)
layout(matrix(c(1,2,3,4),2,2))
plot(model1)
finalmodel <- lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight)
summary(finalmodel)
Price_Predict <- predict(model,interval="predict")
Pred_final <- predict(model)
#storing the  pred final values and all other variables.
Final <- cbind(Price,Pred_final,Age_08_04,KM,HP,cc,Doors,Gears,Quarterly_Tax,Weight)
View(Final)
plot(Final)
